# Generated by Django 4.2.3 on 2023-08-17 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=15)),
                ('gst_number', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=23)),
                ('state', models.CharField(max_length=23)),
                ('adderess', models.CharField(max_length=34)),
            ],
        ),
        migrations.CreateModel(
            name='Add_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
                ('quantity', models.IntegerField(max_length=34)),
                ('amount', models.IntegerField(max_length=34)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.client_detail')),
            ],
        ),
    ]
