# Generated by Django 4.2.3 on 2023-08-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_alter_add_service_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_detail',
            old_name='adderess',
            new_name='address',
        ),
    ]
