# Generated by Django 4.2.3 on 2023-08-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_rename_adderess_client_detail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_detail',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
