# Generated by Django 4.2.3 on 2023-10-07 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_addservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 10, 7, 0, 0)),
            preserve_default=False,
        ),
    ]
