# Generated by Django 4.2.3 on 2023-10-08 17:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_client_detail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 10, 8, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addservice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AddService', to='inv.client_detail'),
        ),
    ]
